apiVersion: v2
name: badgr
description: A Helm chart to deploy the badgr-server
version: 1.0.1
appVersion: 5.7.30
home: https://github.com/WHOAcademy/badgr-server
dependencies:
- name: mysql
  version: "8.0.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: managedDatabase.disabled
maintainers:
  - name: gkmahendran09 
  - name: krishnamadhavan

