apiVersion: v1
name: badgr
version: 1.0.0
appVersion: 5.7.30
pipelineVersion: 1.1.0
# description: Fast, reliable, scalable, and easy to use open-source relational database system.
keywords:
- mysql
- database
- sql
- badgr
home: https://www.mysql.com/
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
sources:
- https://github.com/kubernetes/charts
- https://github.com/docker-library/mysql
engine: gotpl
