image_repository: azurecr.io
image_name: badgr-server
image_namespace: whoalxp
# likely over written by the Argo definition
image_tag: 0.2.0

serverName: badgr

env:
  badgr_username: whoa
  badgr_email: whoa@who.int
  badgr_password: YH5931FW29MREPJMJAF4OAMQQK9V528X9TDV5H1U

# File storage settings
# https://github.com/WHOAcademy/lxp-docs/blob/master/docs/Creating_new_storageclass.adoc
storage:
  enabled: true
  volume_capacity: 2Gi
  storageClassName: azure-file-storage
  mountPath: /badgr_server/mediafiles


# OCP route
route: 
  # enable the OCP route
  enabled: true
  # enable https and auto redirect http to https
  https_redirect: false
  # configure the custom host name
  # by default openshift will assign a host name
  # if it is a private cluster it will assign the private route
  # else the public route
  custom_host:
    enabled: false
    name: badgr-badgr-labs-staging.apps.dev.lxp.academy.who.int

# https://artifacthub.io/packages/helm/bitnami/mysql#parameters
mysql:
  primary:
    persistence:
      enabled: true
      size: 1Gi
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    startupProbe:
      enabled: false
  secondary:
    persistence:
      enabled: false
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    startupProbe:
      enabled: false
  auth:
    rootPassword: pAssw0rd
    database: badgr_server
    username: my-user
    password: password  # TODO: encrypt data 

managed_mysql:
  # disabled: true - to use in-cluster database
  # disabled: false - use managed RDBMS database 
  disabled: true
  # values will be overridden by the config repo based on the namespace
  # different values for database will be available in values-*.yaml file from the config repo
  auth:
    username: badgradmindev
    password: zAxc%768@![DgHF0*
    database: badgr
    host: badgr-mysql-test.mysql.database.azure.com
    port: 3306

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  cpuTarget: 200m
  memTarget: 750Mi
  cpuLimit: 400m
  memLimit: 1536Mi
