## mysql image version
## ref: https://hub.docker.com/r/library/mysql/tags/
##

##
# Docker deets
replicas: 1
badgr_image_repository: azurecr.io
badgr_image_name: badgr-server
badgr_image_namespace: whoalxp
# likely over written by the Argo definition
badgr_image_tag: 0.2.0

# File storage settings
# https://github.com/WHOAcademy/lxp-docs/blob/master/docs/Creating_new_storageclass.adoc
storage:
  enabled: true
  # 595 photos can be stored in a 1Gi storage as an average, we can increase this based 
  # on the requirement for other environments
  volume_capacity: 2Gi
  storageClassName: azure-file-storage
  mountPath: /badgr_server/mediafiles

env:
  badgrUserName: whoa
  badgrEmail: whoa@who.int
  badgrPassword: YH5931FW29MREPJMJAF4OAMQQK9V528X9TDV5H1U

# https://artifacthub.io/packages/helm/bitnami/mysql#parameters
mysql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: false
    service:
      port: 3306
  secondary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      enabled: false
    service:
      port: 3306
  image:
    registry: whoalxp.azurecr.io
    repository: whoa-mysql
    tag: "1.1"
    pullSecrets: ["who-lxp-imagepusher-secret"]
  auth:
    rootPassword: password
    database: badgr
    username: my-user
    password: my-password  # TODO: encrypt data 

managedDatabase:
  #enabled: false to use in-cluster database
  #enabled: true to use managed RDBMS database
  enabled: false
  # values will be overridden by the config repo based on the namespace
  # different values for database will be available in values-*.yaml file from the config repo
  auth:
    host: dummyval
    username: dummyval
    database: dummyval
    password: dummyval
    port: 3306

testFramework:
  enabled: false
  image: "bats/bats"
  tag: "1.2.1"
  imagePullPolicy: IfNotPresent
  securityContext: {}

# OCP route
route: 
  # enable the OCP route
  enabled: true
  # enable https and auto redirect http to https
  https_redirect: false
  # configure the custom host name
  # by default openshift will assign a host name
  # if it is a private cluster it will assign the private route
  # else the public route
  custom_host:
    enabled: false
    name: badgr-badgr-labs-staging.apps.dev.lxp.academy.who.int

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  cpuTarget: 200m
  memTarget: 750Mi
  cpuLimit: 400m
  memLimit: 1.5Gi
