# A dockerized badgr-server stack to emulate a production build
version: '3.3'
services:

  # this container copies in the project code and runs the app with uwsgi
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile.openshift.test.api
    depends_on:
      - "db"
      - "memcached"
    # command: 'sh "/badgr_server/daemon.sh'
    environment:
      - MYSQL_DB_NAME=badgr
      - MYSQL_DB_USER=root
      - MYSQL_DB_PASSWORD=password
      - MYSQL_DB_HOST=db
    networks:
      - badgr
    ports:
        - "8080:8080"

  # this container runs memcached
  memcached:
    image: 'bitnami/memcached:latest'
    expose:
      - "11211"
    networks:
      - badgr

  # this container runs mysql (database)
  db:
    image: mysql:5.6.39
    volumes:
    #   - badgr_server_prod_db:/var/lib/mysql:rw
      - ./.docker/etc/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - "MYSQL_PASSWORD=password"
      - "MYSQL_HOST=db"
      - "MYSQL_ROOT_PASSWORD=password"
    expose:
      - "3306"
    networks:
      - badgr

networks:
  badgr:
    driver: bridge

# volumes:
#   badgr_server_prod_db: