# A dockerized badgr-server stack to emulate a production build
version: '3.3'
services:

  # this container copies in the project code and runs the app with uwsgi
  api_ecs:
    build:
      context: .
      dockerfile: .docker/azure_deployment/Dockerfile.prod.azure
    command: 'sh "/badgr_server/daemon.sh"'
    ports:
      - "8000:8080"
    environment:
      - BADGR_DB_NAME=
      - BADGR_USERNAME=
      - BADGR_PASSWORD=
      - BADGR_DB_HOST=
      - BADGR_DB_PORT=
      - AZURE_ACCOUNT_NAME=
      - AZURE_ACCOUNT_KEY=
      - AZURE_CONNECTION_STRING=
      - AZURE_CONTAINER=