apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serverName }}-service
  labels:
    app: {{ .Values.serverName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ .Values.serverName }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080