apiVersion: v1
kind: Service
metadata:
  name: {{ include "badgr.fullname" . }}
  labels:
    {{- include "badgr.labels" . | nindent 4 }}
  annotations:
    description: Exposes and load balances the application pods got chitchat
spec:
  selector:
     {{- include "badgr.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080