kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ include "badgr.fullname" . }}
  labels:
    {{- include "badgr.labels" . | nindent 4 }}
spec:
  triggers:
    - type: ConfigChange
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    {{- include "badgr.selectorLabels" . | nindent 4 }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        {{- include "badgr.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - resources:
            requests:
              cpu: {{ .Values.hpa.cpuTarget }}
              memory: {{ .Values.hpa.memTarget }}
            limits:
              cpu: {{ .Values.hpa.cpuLimit }}
              memory: {{ .Values.hpa.memLimit }}
          terminationMessagePath: /dev/termination-log
          name: {{ include "badgr.name" . }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          env:
          {{- if .Values.managedDatabase.enabled }}
            - name: MYSQL_DB_HOST
              value: "{{ .Values.managedDatabase.auth.host }}"
            - name: MYSQL_DB_USER
              value: "{{ .Values.managedDatabase.auth.username }}"
            - name: MYSQL_DB_NAME
              value: "{{ .Values.managedDatabase.auth.database }}"
            - name: MYSQL_DB_PASSWORD
              value: "{{ .Values.managedDatabase.auth.password }}"
          {{- else }}
            - name: MYSQL_DB_HOST
              value: "{{ .Release.Name }}-mysql"
            - name: MYSQL_DB_USER
              value: "{{ .Values.mysql.auth.username }}"
            - name: MYSQL_DB_NAME
              value: "{{ .Values.mysql.auth.database }}"
            - name: MYSQL_DB_PASSWORD
              value: "{{ .Values.mysql.auth.password }}"
            - name: DATABASE_SERVICE_PORT
              value: "{{ .Values.mysql.primary.service.port }}"
          {{- end }}
            - name: BADGR_USERNAME
              value: {{ .Values.env.badgrUserName }}
            - name: BADGR_EMAIL
              value: {{ .Values.env.badgrEmail }}
            - name: BADGR_PASSWORD
              value: {{ .Values.env.badgrPassword }}
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          volumeMounts:
          - name: "badgr-media"
            mountPath: {{ .Values.badgr_storage.mountPath }}
          image: "{{ .Values.badgr_image_namespace }}.{{ .Values.badgr_image_repository }}/{{ .Values.badgr_image_name }}:{{ .Values.badgr_image_tag }}"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
    {{- if .Values.badgr_storage.enabled }}
      - name: badgr-media
        persistentVolumeClaim:
          claimName: {{ include "badgr.fullname" . }}
    {{- else }}
      - name: badgr-media
        emptyDir: {}
    {{- end }}