{{- if not .Values.sealed_secrets.disabled }}

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: "{{ include "badgr.fullname" . }}-app-secret"
spec:
  encryptedData:
    badgr_username: {{ .Values.sealed_secrets.app.badgr_username }}
    badgr_email: {{ .Values.sealed_secrets.app.badgr_email }}
    badgr_password: {{ .Values.sealed_secrets.app.badgr_password }}    
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: "{{ include "badgr.fullname" . }}-incluster-secret"


{{- if .Values.managed_mysql.disabled }}

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: "{{ include "badgr.fullname" . }}-incluster-secret"
spec:
  encryptedData:
    mysql_db_name: {{ .Values.sealed_secrets.mysql.mysql_db_name }}
    mysql_db_user: {{ .Values.sealed_secrets.mysql.mysql_db_name }}
    mysql_db_password: {{ .Values.sealed_secrets.mysql.mysql_db_password }}    
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: "{{ include "badgr.fullname" . }}-incluster-secret"

{{- else }}

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: "{{ include "badgr.fullname" . }}-managed-secret"
spec:
  encryptedData:
    mysql_db_host: {{ .Values.sealed_secrets.mysql.mysql_db_host }}
    mysql_db_name: {{ .Values.sealed_secrets.mysql.mysql_db_name }}
    mysql_db_user: {{ .Values.sealed_secrets.mysql.mysql_db_name }}
    mysql_db_password: {{ .Values.sealed_secrets.mysql.mysql_db_password }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: "{{ include "badgr.fullname" . }}-managed-secret"

{{- end }}

{{- end }}