FROM python:3.7-slim

# Create a group and user to run our app
ARG APP_USER=1000650001
ARG APP_GROUP=1000650000
# RUN groupadd -r ${APP_GROUP} && useradd --no-log-init -r -g ${APP_GROUP} ${APP_USER}

RUN mkdir /badgr_server
WORKDIR /badgr_server

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y default-libmysqlclient-dev \
                       python3-dev \
                       python3-cairo \
                       build-essential \
                       xmlsec1 \
                       libxmlsec1-dev \
                       pkg-config \
                       nginx \
                       supervisor

COPY requirements.txt                   /badgr_server

RUN pip install uwsgi
RUN pip install -r requirements.txt

COPY .docker/ecs_deployment/nginx.conf /etc/nginx/nginx.conf
COPY .docker/ecs_deployment/site.conf /etc/nginx/conf.d/
COPY .docker/ecs_deployment/supervisord.conf /etc/supervisor/

COPY manage.py                          /badgr_server
COPY .docker/ecs_deployment/uwsgi.ini              /badgr_server
COPY .docker/ecs_deployment/wsgi.py                /badgr_server
COPY apps                               /badgr_server/apps
COPY .docker/ecs_deployment/daemon.sh /badgr_server

# COPY .docker/ecs_deployment/aws /badgr_server/apps/mainsite/aws

COPY .docker/etc/settings_local.prod.py /badgr_server/apps/mainsite/settings_local.py


# touch folders for nginx
RUN mkdir /var/cache/nginx

## add permissions for nginx user
RUN chown -R ${APP_USER}:${APP_GROUP} /badgr_server && chmod -R 755 /badgr_server && \
        chown -R ${APP_USER}:${APP_GROUP} /var/cache/nginx && \
        chown -R ${APP_USER}:${APP_GROUP} /var/lib/nginx && \
        chown -R ${APP_USER}:${APP_GROUP} /var/log/nginx && \
        chown -R ${APP_USER}:${APP_GROUP} /etc/nginx/conf.d
RUN touch /var/run/nginx.pid && \
        chown -R ${APP_USER}:${APP_GROUP} /var/run/nginx.pid

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

# Change to a non-root user
USER ${APP_USER}:${APP_GROUP}

EXPOSE 8080

CMD sh "/badgr_server/daemon.sh"
